### ISSUE TITLE
How to add new style?

### ISSUE THREAD

**Issue by kishoreg1980** [mdmower/doi-resolver-chrome#6]
Hi 

  Nice app!! I need "Journal of Atmospheric and Solarterrial Physics" style . It is not available here. How can I add to styles?

Thank you in advance,

Kishore

**Comment by mdmower** [comment]
Thank you.

The citation styles are pulled from https://github.com/citation-style-language/styles . If someone [contributes](http://citationstyles.org/developers/) a CSL to that project, I'll be able to pull in into this extension.
