### ISSUE TITLE
Feature request: firefox port

### ISSUE THREAD

**Issue by BrainDamage** [mdmower/doi-resolver-chrome#7]
Would it be possible to have a firefox version? I think with the apis being rather similar it shouldn't be too much efforts

**Comment by mdmower** [comment]
Thanks for your interest (and I really like Mozilla & Firefox) but I don't have plans to port the extension to other browsers. I can barely dedicate enough free time to support one platform.

**Comment by mdmower** [comment]
Finally admitting to myself that I don't plan to work on a Firefox port, so I'm going to close this issue. Sorry, this project is mostly in maintenance mode these days.

**Comment by mdmower** [comment]
I got around to this a couple of months ago: https://addons.mozilla.org/en-US/firefox/addon/doi-resolver/
